version: '3'

services:
  app_cont:
    build: .
    command: gunicorn --access-logfile - --bind :8000 backend.wsgi:application
    volumes:
      - static_volume:/app/static
    networks:
      - postgres-network
    environment:
      - ENV_FILE=.env.prod
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    expose:
      - "8000"

  postgres_db:
    image: postgres:latest
    env_file:
      - postgres.env
    networks:
      - postgres-network
    ports:
      - "5432:5432"

networks:
  postgres-network:
    driver: bridge

volumes:
  static_volume: